FROM alpine:3
RUN dd if=/dev/random bs=1M count=500 of=chunk1
RUN dd if=/dev/random bs=1M count=1000 of=chunk2
RUN dd if=/dev/random bs=1M count=2000 of=chunk3
RUN dd if=/dev/random bs=1M count=5000 of=chunk4
RUN dd if=/dev/random bs=1M count=8000 of=chunk5